version: "3.7"
services:
    proxy:
      build: .
      container_name: "proxy"
      ports:
          - '443:443'
      environment:
          - SSL_CRT_PATH="${SSL_CRT_PATH}"
          - SSL_KEY_PATH="${SSL_KEY_PATH}"
      volumes:
          - type: bind
            source: ./p-drum/img
            target: /www/app/p-drum/img
          - type: bind
            source: ./p-drum/audio
            target: /www/app/p-drum/audio
          - type: volume
            source: public
            target: /www/app
          - type: bind
            source: /etc/letsencrypt/
            target: /etc/letsencrypt/
            read_only: true
      networks:
          - mynet
      command: /bin/sh -c "envsubst '$$SSL_CRT_PATH$$SSL_KEY_PATH' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      #      restart: unless-stopped

volumes:
    public:
        external: true

networks:
    mynet:
        external: true
