version: "3.7"
services:
    proxy:
      image: nginx
      container_name: "proxy"
      ports:
          - '443:443'
      environment:
          - SSL_CRT_PATH="${SSL_CRT_PATH}"
          - SSL_KEY_PATH="${SSL_KEY_PATH}"
      volumes:
          - type: bind
            source: ./nginx
            target: /etc/nginx/conf.d
          - type: volume
            source: out
            target: /www/app/p-drum
            read_only: true
          - type: bind
            source: /etc/letsencrypt/
            target: /etc/letsencrypt/
            read_only: true
      command: /bin/sh -c "envsubst '$$SSL_CRT_PATH$$SSL_KEY_PATH' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      restart: unless-stopped

volumes:
    out:
        external: true

networks:
    mynet:
        external: true
